### ISSUE TITLE
US8: Styling

### ISSUE THREAD

**Issue by ThysBat** [ThysBat/worldbuilding-tool#13]
As a User
I want to have a consistent styling throughout the app,
in order to ensure a visually appealing user experience.

Description
With this US the final colors, layout and general appearance of my app will be set. There will be a lot of refactoring and summarizing spaces as variables.

Acceptance Criteria
- [ ] All components are styled consistently
- [ ] A consistent color scheme is recognizable
- [ ] There is some visual feedback for user interactions

Tasks
- [ ] pick 2-3 colors to use
- [ ] set different variables in different sizes for colors, margin, padding, etc..
- [ ] adjust components with declared variables and additional styling

**Comment by matschi3** [comment]
time for styling 😎
LGTM!
great to use variables for lot of stuff 👍🏼
